#!/bin/sh

deps(){
    go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    go get golang.org/x/net/http2
}

proto(){
    protoc --go_out=. --go-grpc_out=. protogen/account.proto
}

setenvs(){
    export DB_USER=tydes
    export DB_PASS=pass
    export DB_HOST=localhost:5432
    export DB_NAME=lms_accounts
}

run(){
    setenvs
    go run server.go
}

$1
