#!/bin/sh

deps(){
	go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
	go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	go get golang.org/x/net/http2
}

proto(){
	protoc --go_out=../../protogen/go       --go_opt=paths=source_relative \
	       --go-grpc_out=../../protogen/go  --go-grpc_opt=paths=source_relative \
		   ./book.proto
}

run(){
	go run ./server.go
}
$1
